---
title: "genotype"
execute:
  echo: false
  warning: false
  message: false
format: html
---

```{r}
source("functions.R")
```

```{r}
library(tidyverse)
library(reshape2)
library(ggplot2)
library(ggtext)
library(vdjbasevis)
```

```{r}

df<-read.csv("C:/Users/admin/Documents/master/macca/ref_2024_03_20/25_IGM_genotype_ref_2024_20_03.tsv", sep="\t")

load("2024-03-20_gene_igh_names.rda")
load("2024-20-03_gene.usage.df.rda")


```

```{r}
allele_palette_new <-vdjbasevis:::ALLELE_PALETTE
names(allele_palette_new) <- c("01" ,"02", "03", "04" ,"05", "06", "07","08" ,"09" ,"10", "11", "12", "13", "14", "15",
                               "16" ,"17", "18", "19", "20" ,"21" ,"22" ,"23" ,"24", "25" ,"26", "28", "29", "31", "32","NA")

colnames(df)<-c("gene","alleles","counts","total","note","kh","kd","kt","kq","k_diff","genotyped_alleles","Freq_by_Clone","freq_by_seq","subject","file")
df<-df[grepl("IGHV",df$gene),]

genes.usage.df$subject <- sapply(str_split(genes.usage.df$subject, "\\."), function(x) x[[2]])
genes.usage.df<-genes.usage.df[grepl("IGHV",genes.usage.df$gene),]
```


```{r}
df_expanded <- df %>%
  separate_rows(genotyped_alleles, sep = ",") %>%
  mutate(genotyped_alleles = as.factor(genotyped_alleles)) %>%
  group_by(gene, subject) %>%
  mutate(n = n(), idx = row_number()) %>%
  ungroup()
```

```{r}
usage_combination <- unique(genes.usage.df[, c("gene", "subject", "frac")])
usage_combination$in_df_usage<-TRUE

filter_gene_sequence_names<-unique(genes.usage.df$gene)

all_combinations <- expand.grid(gene = filter_gene_sequence_names, 
                               subject = unique(df$subject))
existing_combinations <- unique(df_expanded[, c("gene", "subject")])
existing_combinations_df <- as.data.frame(existing_combinations)
existing_combinations_df$in_df_expanded <- TRUE

# Perform a left join
merged_df <- merge(all_combinations, existing_combinations_df, by = c("gene", "subject"), all.x = TRUE)
# Filter to find missing combinations
missing_combinations <- subset(merged_df, is.na(in_df_expanded))
# Perform a left join
merged_df <- merge(missing_combinations, usage_combination, by = c("gene", "subject"), all.x = TRUE)
# Filter to find missing combinations
missing_combinations <- subset(merged_df, frac>0)
# Select only the relevant columns
missing_combinations <- missing_combinations[, c("gene", "subject")]

missing_combinations$genotyped_alleles <- NA
missing_combinations$n <- 1  # Assign an appropriate value
missing_combinations$idx <- 1
missing_combinations$alleles <- NA  # or appropriate default value
missing_combinations$counts <- NA   # or appropriate default value
missing_combinations$total <- NA    # or appropriate default value
missing_combinations$note <- NA     # or appropriate default value
missing_combinations$kh <- NA       # or appropriate default value
missing_combinations$kd <- NA       # or appropriate default value
missing_combinations$kt <- NA       # or appropriate default value
missing_combinations$kq <- NA       # or appropriate default value
missing_combinations$k_diff <- NA   # or appropriate default value
missing_combinations$Freq_by_Clone <-NA
missing_combinations$freq_by_seq<-NA
missing_combinations$file <- NA     # or appropriate default value

# Now df_expanded and missing_combinations have the same structure
c <- rbind(df_expanded, missing_combinations)
```


```{r}
df_expanded <- df_expanded %>%
  mutate(subject_idx = as.numeric(factor(subject)),
         gene_idx = as.numeric(factor(gene)))


df_expanded<- df_expanded %>%
  mutate(modified_allele = ifelse(grepl("_", genotyped_alleles),
                                  sub("_.*", "", genotyped_alleles),
                                  as.character(genotyped_alleles)))

unique_alleles <- unique(df_expanded$genotyped_alleles)
unique_modified_alleles <- unique(df_expanded$modified_allele)

# Initialize allele_palette_modified with colors from allele_palette_new
allele_palette_modified <- allele_palette_new

# Loop through the unique_modified_alleles to assign colors
for (allele in unique_alleles) {
  if (!(allele %in% names(allele_palette_new))) {
    # If the modified allele is not in allele_palette_new, assign a new color
    # This could be a default color or based on some logic
    allele_palette_modified[allele] <-  allele_palette_new[sub("_.*", "", allele)]
  } else {
    # If the allele already exists in allele_palette_new, use its color
    allele_palette_modified[allele] <- allele_palette_new[allele]
  }
}

unique_alleles_with_underscore <- df_expanded %>%
  arrange(genotyped_alleles)%>%
  filter(grepl("_", genotyped_alleles)) %>%
  distinct(genotyped_alleles) %>%
  mutate(underscore_number = seq_along(genotyped_alleles))

df_expanded <- df_expanded %>%
  left_join(unique_alleles_with_underscore, by = "genotyped_alleles") %>%
  mutate(underscore_number = ifelse(is.na(underscore_number), NA_integer_, underscore_number))

df_expanded <- df_expanded %>%
  mutate(has_underscore = grepl("_", genotyped_alleles))

legend_data <- df_expanded %>%
  distinct(genotyped_alleles, underscore_number) %>%
  mutate(legend_label = ifelse(is.na(underscore_number),
                               as.character(genotyped_alleles),
                               paste(underscore_number, "^" ,genotyped_alleles, sep = ""))) %>%
  arrange(genotyped_alleles)

```

```{r}
p<-ggplot(df_expanded, aes(xmin = subject_idx - 0.5 + (idx-1)/n, xmax = subject_idx - 0.5 + idx/n,
                        ymin = gene_idx - 0.5, ymax = gene_idx + 0.5)) +
  geom_rect(aes(fill = genotyped_alleles)) +
  geom_text(data = subset(df_expanded, has_underscore), 
            aes(x = subject_idx - 0.5 + (idx-0.5)/n, y = gene_idx, label =   paste( "^" ,underscore_number, sep = "")), 
            vjust = 0.5, hjust = 0.5, 
            size = 2)  +
  scale_fill_manual(values = allele_palette_modified, name = " ",
                    breaks = legend_data$genotyped_alleles,
                    labels = legend_data$legend_label) +
  scale_x_continuous(breaks = df_expanded$subject_idx, labels = df_expanded$subject) +
  scale_y_continuous(breaks = df_expanded$gene_idx, labels = df_expanded$gene) +
  theme_minimal() +
  geom_vline(xintercept = unique(df_expanded$subject_idx) - 0.5, color = "black", size = 0.5) +
  geom_hline(yintercept = unique(df_expanded$gene_idx) - 0.5, color = "black", size = 0.5) +
  labs(fill = " ", x = " ", y = " ") +
  theme(axis.text.x = element_text(angle = 90, hjust = 0.5, vjust = 0.5, size = 10),
        axis.text.y = element_text(angle = 0, hjust = 0.5, size = 10),
        legend.position = "none",
        legend.key.size = unit(0.3, "cm"))

# Filter rows where k_diff < 1
df_diagonal <- df_expanded %>%
  filter(k_diff < 1)

p<-p + geom_segment(data = df_diagonal, 
                 aes(x = subject_idx - 0.45, y = gene_idx - 0.45, 
                     xend = subject_idx - 0.45 +1, yend = gene_idx + 0.55), 
                 color = "black", size = 0.5)

```


```{r}
ggplotly(p, tooltip = c("genotyped_alleles", "text"))%>%
  layout(
    autosize = F,
    width = 900,
    height = 2500
  )
```

